language: node_js
node_js:
  - 0.8
  - 0.6
before_script:
  - npm install connect
  - sudo node test/js/server.js ../../ 80 &
  - sleep 5
script: phantomjs test/qunit/run-qunit.js "http://localhost:80/test/index.html"